#!/bin/bash

# Usage:
# ./conv data.csv src dst
# copy files from src/* -> dst/*
# based on csv file
# skipping first line

set -euo pipefail
export PATH=/bin:/sbin:/usr/bin:/usr/local/bin

if [[ "$#" -ne 3 ]]; then
  echo "Usage: $0 <csv-file> <src-dir> <dst-dir>"
  exit 1
fi

csv="$1"
src="$2"
dst="$3"

exec < "$csv"

read -r junk

while read -r line
do
  id=$(echo "$line" | cut -d, -f1)
  n1=$(echo "$line" | cut -d, -f2)
  n2=$(echo "$line" | cut -d, -f3)
  srcf=$(find "$src" -name "*$n1*$n2*.jpg")
  if [[ ! -f "$srcf" ]]; then
    echo "Cannot handle this: $n1 $n2: $srcf"
    continue
  fi
  dstf="$dst/$id.jpg"
  if [[ -f "$dstf" ]]; then
    echo "Destination file already exists: $dstf ($n1 $n2)"
    continue
  fi
  cp "$srcf" "$dstf"
done
